server:
  port: 8080
  #server.servlet.context-path=/api


spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost:5432}/my_payments
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true

  flyway:
    enabled: true
    url: jdbc:postgresql://${DATABASE_URL:localhost:5432}/my_payments
    schemas: public
    defaultSchema: public #// default schema is importent
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    baseline-on-migrate: true

  #file config
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

  springdoc:
    swagger-ui:
      disable-swagger-default-ur: true

#springdoc-swagger-ui.path=/swagger-ui.html
#springdoc.api-docs.path=/api-docs
#springdoc.swagger-ui.operationsSorter=method